### ISSUE TITLE
unless statement not parsed

### ISSUE THREAD

**Issue by MapTo0** [blikblum/to-htm#1]
I just tried to run

```
<div>
    {{#if test}}
        <h1>aaa</h1>
    {{/if}}
    
    {{#unless test}}
        <h1>aaa</h1>
    {{/unless}}
</div>
```

and error `Error: Unexpected unless statement` appears.
Will this be working? 

P.S. other Handlebars build in helpers like `else` in the if are also not working.
In case these are limitations - could you please list them in the README?

Tested in: https://blikblum.github.io/to-htm/web/dist/

**Comment by blikblum** [comment]
It's a limitation of the library used to parse handlebars tracked at https://github.com/danakt/handlebars-to-jsx/issues/5

**Comment by blikblum** [comment]
Created a PR there

**Comment by blikblum** [comment]
Current version fixes this issue among others
